language: ruby
sudo: false
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.1.0"
  - ree
before_install: gem install bundler # Fix bundler issues on 1.9.3
before_script: rake travis_ci:prepare
script: rake all:bundle all:spec
notifications:
  email:
    - fail@makandra.de
branches:
  only:
    - master
    - travis-testing
