language: ruby

sudo: false

cache: bundler

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3

gemfile:
  - Gemfile.3-2
  - Gemfile.4-2
  - Gemfile.5-2
  - Gemfile.6-0

matrix:
  exclude:
    - gemfile: Gemfile.3-2
      rvm: 2.4.5
    - gemfile: Gemfile.3-2
      rvm: 2.5.3
    - gemfile: Gemfile.4-2
      rvm: 2.5.3
    - gemfile: Gemfile.6-0
      rvm: 2.3.8
    - gemfile: Gemfile.6-0
      rvm: 2.4.5

install:
  # Replace default Travis CI bundler script with a version that doesn't
  # explode when lockfile doesn't match recently bumped version
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

script: bundle exec rake current_rspec

notifications:
  email:
    - fail@makandra.de
