language: ruby

sudo: false

cache: bundler

rvm:
  - 1.8.7
  - 2.1.8
  - 2.4.1

gemfile:
  - gemfiles/Gemfile.3-2
  - gemfiles/Gemfile.4-2
  - gemfiles/Gemfile.5-2

matrix:
  exclude:
    - gemfile: gemfiles/Gemfile.3-2
      rvm: 2.4.1
    - gemfile: gemfiles/Gemfile.4-2
      rvm: 1.8.7
    - gemfile: gemfiles/Gemfile.5-2
      rvm: 1.8.7
    - gemfile: gemfiles/Gemfile.5-2
      rvm: 2.1.8


install:
  # Replace default Travis CI bundler script with a version that doesn't
  # explode when lockfile doesn't match recently bumped version
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

script: bundle exec rake current_rspec

notifications:
  email:
    - fail@makandra.de
